import type { FleetTruck } from "@/types";

export const FLEET: FleetTruck[] = [
  {
    id: "light-truck",
    name: "Light Truck",
    category: "Light Duty",
    capacity: "Up to 3 Tonnes",
    suitableCargo: ["Retail Stock", "Furniture", "Small Equipment", "Parcels"],
    availability: "Available Now",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "medium-truck",
    name: "Medium Truck",
    category: "Medium Duty",
    capacity: "3 – 10 Tonnes",
    suitableCargo: ["Building Materials", "Packaged Goods", "Farm Produce"],
    availability: "Available Now",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "heavy-truck",
    name: "Heavy Truck",
    category: "Heavy Duty",
    capacity: "10 – 20 Tonnes",
    suitableCargo: ["Bulk Cement", "Steel", "Machinery", "Aggregates"],
    availability: "Limited Availability",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "trailer",
    name: "Trailer",
    category: "Long Haul",
    capacity: "20 – 30 Tonnes",
    suitableCargo: ["Bulk Grain", "Containers", "Industrial Cargo"],
    availability: "Available Now",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "flatbed",
    name: "Flatbed",
    category: "Open Deck",
    capacity: "Up to 25 Tonnes",
    suitableCargo: ["Timber", "Pipes", "Construction Equipment"],
    availability: "Available Now",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "container",
    name: "Container Truck",
    category: "Containerized",
    capacity: "20ft / 40ft",
    suitableCargo: ["Export Goods", "Sealed Cargo", "Import Shipments"],
    availability: "High Demand",
    image: "/images/zigo-hero-truck.png",
  },
  {
    id: "refrigerated",
    name: "Refrigerated Truck",
    category: "Cold Chain",
    capacity: "Up to 12 Tonnes",
    suitableCargo: ["Dairy", "Fresh Produce", "Pharmaceuticals"],
    availability: "Limited Availability",
    image: "/images/zigo-hero-truck.png",
  },
];
